"""empty message

Revision ID: 2b1f3d04a8de
Revises: 51122360a73c
Create Date: 2014-05-14 10:33:57.370234

"""

# revision identifiers, used by Alembic.
revision = '2b1f3d04a8de'
down_revision = '51122360a73c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('custom_notification_settings')
    op.drop_table('custom_notifications')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_notifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=False),
    sa.Column('type', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_notification_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('custom_notification_id', sa.INTEGER(), nullable=True),
    sa.Column('message_type', sa.INTEGER(), nullable=False),
    sa.Column('message_address_or_serial', sa.INTEGER(), nullable=True),
    sa.Column('message_channel', sa.INTEGER(), nullable=True),
    sa.Column('message_data', sa.INTEGER(), nullable=True),
    sa.Column('custom_alert_message', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['custom_notification_id'], [u'custom_notifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('notification_messages')
    ### end Alembic commands ###
