"""Custom button support

Revision ID: 2d1953265871
Revises: 2b1f3d04a8de
Create Date: 2014-09-08 12:00:59.445910

"""

# revision identifiers, used by Alembic.
revision = '2d1953265871'
down_revision = '2b1f3d04a8de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buttons',
    sa.Column('button_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('button_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buttons')
    ### end Alembic commands ###
