"""Added failed login table.

Revision ID: 76ed239fa861
Revises: fdc8fd4be3c0
Create Date: 2016-02-18 15:28:04.037196

"""

# revision identifiers, used by Alembic.
revision = '76ed239fa861'
down_revision = 'fdc8fd4be3c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('user_agent_string', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('failed_login_attempts')
    ### end Alembic commands ###
