"""Added apikeys table.

Revision ID: 823cb6eb9df4
Revises: 76ed239fa861
Create Date: 2016-02-19 12:25:18.473105

"""

# revision identifiers, used by Alembic.
revision = '823cb6eb9df4'
down_revision = '76ed239fa861'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apikeys')
    ### end Alembic commands ###
